import type {Metadata} from 'next';
import Image from 'next/image';
import {PageShell} from '@/components/corra/page-shell';
import {CTA} from '@/components/corra/cta';
export const metadata:Metadata={title:'About Corra — From chaos to clarity',description:'Why Corra connects two phase-aware protein formulas with a simpler way to understand your cycle.'};

export default function About(){return <PageShell className="about-page">
  <section className="about-opening page-width"><div className="about-opening-copy"><span className="eyebrow">WHY CORRA EXISTS</span><h1 className="inner-title">Your body changes.<br/><em>Let’s make sense of it.</em></h1><p>Hormones. Symptoms. Changing nutritional needs. There’s a lot to understand—and a lot of noise around it.</p><p>Corra begins with one idea: make the connection between your body and your daily nutrition easier to follow.</p><span className="about-signature">CHAOS → CORRA → CLARITY</span></div><figure className="about-opening-image editorial-image page-reveal"><Image src="/images/jogging.webp" alt="A woman running along a coastal path in warm morning light" fill priority sizes="(max-width: 800px) 100vw, 45vw"/><figcaption>FOR A BODY THAT NEVER STANDS STILL.</figcaption></figure></section>
  <section className="about-story page-width"><div className="page-reveal"><span className="eyebrow">LESS TO DECODE</span><h2>A connected<br/><em>approach.</em></h2></div><div className="about-story-copy page-reveal"><p>Nutrition in one place. Cycle information in another. Corra is designed to bring the two together.</p><p>Our first product pairs Follicular vanilla and Luteal chocolate protein. The app concept connects cycle dates and symptom check-ins with guidance on which packet to use and when to switch.</p><p>The packets support your nutrition. The app helps you see your patterns. Each has a clear job.</p></div></section>
  <section className="about-principles page-width" aria-labelledby="principles-heading"><div className="principles-heading page-reveal"><span className="eyebrow">WHAT GUIDES THE DESIGN</span><h2 id="principles-heading">Keep it <em>clear.</em></h2></div><div className="principle-list">{[
    ['01','Explain the connection.','Show how the packets and app work together. Make the next step easy to understand.'],
    ['02','Make space for difference.','Cycles vary. Check-ins should help you notice your own patterns, rather than expect every day to feel the same.'],
    ['03','Start with the essentials.','Two formulas, two flavours and clear product information. Useful details before extra noise.'],
  ].map(([number,title,body])=><article className="page-reveal" key={number}><span>{number}</span><h3>{title}</h3><p>{body}</p></article>)}</div></section>
  <section className="about-future page-width page-reveal"><div className="editorial-image"><Image src="/images/yoga.webp" alt="A woman practising yoga in a sunlit studio" fill sizes="(max-width: 800px) 100vw, 40vw"/></div><div><span className="eyebrow">WHERE WE START. WHERE WE’RE GOING.</span><h2>Built around the cycle.<br/><em>With a wider view.</em></h2><p>Our first product focuses on the menstrual cycle. Corra’s wider vision is to support both women and men with nutrition that reflects changing needs.</p><p>Warm, direct and easy to understand. That’s the experience we’re building.</p><CTA href="/shop">Meet the two formulas</CTA></div></section>
</PageShell>}
