export type ProductId = 'corra-set' | 'follicular' | 'luteal';
export type CorraProduct = {id:ProductId;name:string;subtitle:string;flavour:string;colour:string;tint:string;protein:string;weight:string;description:string;pricePence:number;phase:string;phaseDays:string;routine:string;contents:string;highlights:string[]};
// Prices are placeholders until Corra confirms its pricing. Change them here; the cart, checkout and order API all read from this file.
export const PRICES_ARE_PLACEHOLDERS = true;
export const products:CorraProduct[] = [
{id:'corra-set',name:'The Corra set',subtitle:'Follicular vanilla + Luteal chocolate',flavour:'Vanilla + Chocolate',colour:'#6B1D57',tint:'#eee1e8',protein:'25g / 30g',weight:'2 × 500g',description:'Both Corra formulas, together. One Follicular vanilla pouch and one Luteal chocolate pouch, designed to support your nutrition as your cycle changes.',pricePence:6499,phase:'Both phases',phaseDays:'Follicular days 6–13* · Luteal days 17–28*',routine:'Start with Follicular after your period, then switch to Luteal after ovulation. The Corra app concept is designed to help you know when to switch.',contents:'One 500g Follicular vanilla pouch and one 500g Luteal chocolate pouch.',highlights:['Both formulas in one order','Follicular label: 25g protein · Luteal label: 30g protein','0g added sugar on both labels','20 vitamins & minerals on both labels']},
{id:'follicular',name:'Follicular',subtitle:'Vanilla · 500g',flavour:'Vanilla',colour:'#F95006',tint:'#FFE3D3',protein:'25g',weight:'500g',description:'Vanilla hormone-support protein for your Follicular routine. With 25g protein, 0g added sugar and 20 vitamins & minerals.',pricePence:3499,phase:'Follicular phase',phaseDays:'Days 6–13*',routine:'The phase before ovulation. Use your Follicular pouch for this part of your routine and track how your own rhythm changes.',contents:'One 500g Follicular pouch in vanilla flavour.',highlights:['25g protein, as listed on the label','Vanilla flavour','0g added sugar','20 vitamins & minerals']},
{id:'luteal',name:'Luteal',subtitle:'Chocolate · 500g',flavour:'Chocolate',colour:'#6B1D57',tint:'#eedde8',protein:'30g',weight:'500g',description:'Chocolate hormone-support protein for your Luteal routine. With 30g protein, 0g added sugar and 20 vitamins & minerals.',pricePence:3499,phase:'Luteal phase',phaseDays:'Days 17–28*',routine:'The phase after ovulation. Use your Luteal pouch for this part of your routine and notice your patterns in mood, energy and cravings.',contents:'One 500g Luteal pouch in chocolate flavour.',highlights:['30g protein, as listed on the label','Chocolate flavour','0g added sugar','20 vitamins & minerals']},
];
export function getProduct(id:string){return products.find(p=>p.id===id)}
export function formatPrice(pence:number){return new Intl.NumberFormat('en-GB',{style:'currency',currency:'GBP'}).format(pence/100)}
