'use client';
import {useState,useEffect} from 'react';
import Link from 'next/link';
import Image from 'next/image';
import {usePathname} from 'next/navigation';
import {ArrowUpRight,Menu,X,Mail,ShoppingBag} from 'lucide-react';
import {useCartCount,useCartReady} from '@/lib/cart';
function CartLink(){
 const count=useCartCount();const ready=useCartReady();const shown=ready&&count>0;
 return <Link prefetch={false} href="/cart" className="icon-button cart-link" aria-label={shown?`Cart, ${count} ${count===1?'item':'items'}`:'Cart'}><ShoppingBag size={20}/>{shown&&<span className="cart-count" aria-hidden="true">{count>9?'9+':count}</span>}</Link>
}
export function Navbar(){
 const path=usePathname();const [openPath,setOpenPath]=useState<string|null>(null);const menu=openPath!==null&&openPath===path;
 useEffect(()=>{if(!menu)return;const close=(event:KeyboardEvent)=>{if(event.key==='Escape')setOpenPath(null)};document.addEventListener('keydown',close);return()=>document.removeEventListener('keydown',close)},[menu]);
 const links=[['Shop','/shop'],['About Corra','/about'],['Science','/#science'],['Contact','/contact']];
 return <header className="navbar site-navbar"><nav className="nav-left" aria-label="Main navigation">{links.map(([name,url])=><Link prefetch={false} href={url} key={url} aria-current={path===url?'page':undefined}>{name}</Link>)}</nav><button className="mobile-menu icon-button" aria-label={menu?'Close menu':'Open menu'} aria-controls="corra-mobile-nav" aria-expanded={menu} onClick={()=>setOpenPath(menu?null:path)}>{menu?<X size={22}/>:<Menu size={22}/>}</button><Link prefetch={false} className="nav-logo" href="/" aria-label="Corra home"><Image className="wordmark" src="/images/wordmark-black.png" width={190} height={64} alt="Corra" priority/></Link><div className="nav-right"><Link prefetch={false} href="/contact" className="icon-button nav-contact" aria-label="Contact Corra"><Mail size={20}/></Link><CartLink/><Link prefetch={false} className="small-pill" href="/shop">Explore Corra</Link></div>{menu&&<nav id="corra-mobile-nav" className="mobile-nav" aria-label="Mobile navigation">{[...links,['Your cart','/cart'],['Find your phase','/#phase'],['The Corra app','/#app']].map(([name,url])=><Link prefetch={false} key={url} href={url} onClick={()=>setOpenPath(null)}>{name}<ArrowUpRight size={17}/></Link>)}</nav>}</header>
}
export function Footer(){return <footer className="footer"><div className="footer-upper"><div className="footer-brand"><Link prefetch={false} href="/" aria-label="Corra home"><Image className="circle-logo" src="/images/logo-original.png" width={125} height={125} alt="Corra"/></Link><h3>Less chaos.<br/><em>More clarity.</em></h3><p>Two protein formulas.<br/>Connected to your cycle.</p></div><div className="footer-col"><span>EXPLORE</span><Link prefetch={false} href="/shop">Shop Corra</Link><Link prefetch={false} href="/shop/corra-set">The two-packet set</Link><Link prefetch={false} href="/shop/follicular">Follicular · Vanilla</Link><Link prefetch={false} href="/shop/luteal">Luteal · Chocolate</Link></div><div className="footer-col"><span>CORRA</span><Link prefetch={false} href="/about">About us</Link><Link prefetch={false} href="/#app">The Corra app</Link><Link prefetch={false} href="/#science">Our formula</Link><Link prefetch={false} href="/#faq">FAQs</Link><Link prefetch={false} href="/contact">Contact us</Link></div><div className="footer-invitation"><span className="eyebrow">LET’S CONNECT</span><p>A question?<br/><em>We’re listening.</em></p><Link prefetch={false} href="/contact">Talk to Corra <ArrowUpRight size={20}/></Link></div></div><div className="footer-divider"><span>© {new Date().getFullYear()} Corra.</span><span>CHAOS → CORRA → CLARITY</span><Link prefetch={false} href="/contact" aria-label="Contact Corra"><Mail size={18}/></Link></div><div className="footer-landscape"><Image src="/images/footer-v2.webp" alt="The two Corra protein pouches in a sculptural orange and plum landscape" fill sizes="100vw"/></div></footer>}
